version: '3.1'

services:
  db:
    image: mysql:5.7.25
    command: "--explicit_defaults_for_timestamp --innodb-use-native-aio=0"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./html:/var/www/html
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
